const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,baseline,battle=null,sheet='공격 만들기',mode='battle',history=[],lastTime=0,lastLog='',renderIdle=0,dialoguePreview=null,lastDialogueView='';
const draftKey='yachacha-fullflow-isolated-combat-v1',scene=new (JSON.parse($('host-data').textContent).mode==='story'?StoryScene:GameScene)($('arena'),JSON.parse($('embedded-assets').textContent));
const bools=new Set(['Enabled','IsInitial','CanDefend','BreakTiles','AvoidRepeat','PauseForEntryDialogue','PauseCombat']);
const nums=new Set(['PatternID','ShapePoolID','Candidate','MonsterID','PhaseID','NextPhaseID','PlayerID','MaxHP','GaugeMax','ParryGain','GuardGain','DodgeGain','RecoveryMs','AttackSpeed','PlayerDodgeMissCount','HitDamage','Weight','HitMin','HitMax','GapMinMs','GapMaxMs','ResponseMs','ExtraMinMs','ExtraMaxMs','MoveSpeed','MoveDistance','EffectMs','PushTiles','PushLeadMs','PushMoveMs','DodgeDamage','GuardMax','ParryMs','GuardHitCost','GuardHoldPerSec','GuardRegenPerSec','GuardBreakSec','GroupID','DialogueID','Order','TriggerID','HPThresholdPct','CooldownMs','MaxPerBattle','CPS','HoldMs','GapMs','EntryDialogueGroupID','EventCount','OpeningDamageDisplay']);
const choices={RangeMode:['범위 반복','경로 순차','밀친 위치'],SelectMode:['직접 입력','플레이어 행','플레이어 열'],MoveType:['없음','대상까지','고정 거리'],Effect:['기본','블래스터 레이저'],PushDirection:['왼쪽','오른쪽','위','아래','좌우 무작위'],TransitionTrigger:['HP 0','빈틈공격 성공','없음','미정']};
Object.assign(choices,{ActorEffect:['없음','비틀거림','놀람','식은땀','부활 후 대사'],FinishEffect:['없음','소멸','소울 해금 연출'],Speaker:['몬스터','플레이어','나레이션'],PlaybackMode:['순서대로','무작위 한 줄'],AdvanceMode:['자동','입력'],BeautyCondition:['공통','미용 성공','미용 실패'],EventType:['전투 시작','페이즈 진입','공격 시작','빈틈 발생','빈틈공격 성공','빈틈공격 MISS','몬스터 HP 이하','플레이어 HP 이하','승리','패배']});
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function pauseBattle(){if(battle){battle.paused=true;battle.setGuard(false);scene.stop();$('pause').textContent='계속하기';}}
function remember(){history.push(clone(data));if(history.length>30)history.shift();}
function persist(){let changes=0;for(const s of data.sheets){const orig=baseline.sheets.find(x=>x.name===s.name);changes+=Math.abs(s.rows.length-orig.rows.length);s.rows.forEach((r,i)=>s.keys.forEach(k=>{if(r[k]!==orig.rows[i]?.[k])changes++;}));}$('editCount').textContent=changes?`${changes}개 값 변경`:'변경 없음';$('draftBadge').textContent=changes?'수정한 작업본':'불러온 값';try{if(combatOwnerAllowed())localStorage.setItem(draftKey,JSON.stringify({data,source:JSON.stringify(baseline)}));}catch{}$('undo').disabled=!history.length;}
function edited(){pauseBattle();OfflineBook.refreshNames(data);persist();populate();notice('작업본을 수정했어요. ‘적용 후 시작’으로 다시 시험하고 엑셀로 저장하세요.');}
function selectedMonster(){return rows(data,'몬스터 페이즈').find(m=>same(m.MonsterID,$('monster').value)&&same(m.PhaseID,$('phase').value));}
function selectedPattern(){return rows(data,'공격 만들기').find(p=>same(p.PatternID,$('pattern').value));}
function character(){if($('character').value!=='auto')return $('character').value;const name=battle?.monster.Name||selectedMonster()?.Name||'';return /샌즈|sans/i.test(name)?'sans':/취객|drunk/i.test(name)?'drunk':/좀비|zombie/i.test(name)?'zombie':'unknown';}
function populate(){const mid=$('monster').value,phase=$('phase').value,pid=$('pattern').value;const list=rows(data,'몬스터 페이즈').filter((m,i,a)=>a.findIndex(n=>same(n.MonsterID,m.MonsterID))===i);$('monster').innerHTML=list.map(m=>`<option value="${esc(m.MonsterID)}">${esc(m.Name)} · ${esc(m.MonsterID)}</option>`).join('');if(list.some(m=>same(m.MonsterID,mid)))$('monster').value=mid;const phases=rows(data,'몬스터 페이즈').filter(m=>same(m.MonsterID,$('monster').value));$('phase').innerHTML=phases.map(m=>`<option value="${esc(m.PhaseID)}">${m.PhaseID}페이즈${on(m.IsInitial)?' · 시작':''}</option>`).join('');if(phases.some(m=>same(m.PhaseID,phase)))$('phase').value=phase;else if(phases.some(m=>on(m.IsInitial)))$('phase').value=phases.find(m=>on(m.IsInitial)).PhaseID;
 const patterns=rows(data,'공격 만들기');$('pattern').innerHTML=patterns.map(p=>`<option value="${esc(p.PatternID)}">${esc(p.PatternID)} · ${esc(p.Name)}</option>`).join('');if(patterns.some(p=>same(p.PatternID,pid)))$('pattern').value=pid;populateDialogue();updateInfo();}
function tabs(){$('tabs').innerHTML=data.sheets.map(s=>`<button data-sheet="${esc(s.name)}" class="${sheet===s.name?'active':''}">${esc(s.name)}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{sheet=b.dataset.sheet;$('filter').value='';tabs();table();});}
function unused(r,k){if(sheet!=='공격 만들기')return false;if(['HitMin','HitMax','AvoidRepeat'].includes(k))return r.RangeMode!=='범위 반복';if(k==='TilePath')return r.RangeMode!=='경로 순차';if(k==='ShapePoolID')return r.RangeMode==='밀친 위치';return false;}
function table(){const s=data.sheets.find(s=>s.name===sheet);$('sheetDesc').textContent=s.description;const filter=$('filter').value.toLowerCase();$('editorTable').innerHTML='<thead><tr>'+s.keys.map((k,i)=>`<th data-help="${esc(k)}" tabindex="0" title="${esc(s.notes?.[k]||k)}" class="${['Notes','Description','TilePath','Text'].includes(k)?'wide':''}">${esc(s.labels[i])}<small>${esc(k)}${s.formulaKeys.includes(k)?' · 자동':''}</small></th>`).join('')+'<th>행 편집</th></tr></thead><tbody>'+s.rows.map((r,i)=>{if(filter&&!s.keys.map(k=>r[k]).join(' ').toLowerCase().includes(filter))return '';return '<tr>'+s.keys.map(k=>{const v=r[k],opts=bools.has(k)?(data.layout==='unity'?['TRUE','FALSE']:['켜기','끄기']):choices[k],readonly=s.formulaKeys.includes(k),numeric=nums.has(k)||(sheet==='공통 규칙'&&k==='Value'&&typeof v==='number');let input;
  if(opts){const current=typeof v==='boolean'?(data.layout==='unity'?(v?'TRUE':'FALSE'):(v?'켜기':'끄기')):String(v??'');input=`<select aria-label="${esc(k)}"><option value="">기본값</option>${opts.map(o=>`<option ${current===o?'selected':''}>${o}</option>`).join('')}${current&&!opts.includes(current)?`<option selected>${esc(current)}</option>`:''}</select>`;}else if(k==='Text')input=`<textarea aria-label="대사 내용" rows="2">${esc(v)}</textarea>`;else input=`<input aria-label="${esc(k)}" type="${numeric&&!readonly?'number':'text'}" ${numeric?'step="any"':''} ${readonly?'readonly':''} value="${esc(v)}" placeholder="${readonly?'자동 표시':'빈칸'}" title="${esc(v)}">`;
  const changed=v!==baseline.sheets.find(x=>x.name===sheet).rows[i]?.[k];return `<td data-row="${i}" data-key="${esc(k)}" class="${unused(r,k)?'unused':''} ${changed?'changed':''} ${['Notes','Description','TilePath','Text'].includes(k)?'wide':''}">${input}</td>`;}).join('')+`<td class="actions"><button data-copy="${i}">복제</button><button data-delete="${i}">삭제</button></td></tr>`;}).join('')+'</tbody>';
 const showHelp=k=>{$('columnHelp').innerHTML=`<b>${esc(s.labels[s.keys.indexOf(k)])} · ${esc(k)}</b>\n${esc(s.notes?.[k]||'이 컬럼에 작성된 값을 엑셀에 그대로 저장합니다.')}`;};
 $('editorTable').querySelectorAll('[data-help]').forEach(el=>{el.onclick=()=>showHelp(el.dataset.help);el.onkeydown=e=>{if(e.key==='Enter')showHelp(el.dataset.help);};});
 $('editorTable').querySelectorAll('td input,td select,td textarea').forEach(el=>{el.onfocus=()=>{pauseBattle();showHelp(el.closest('td').dataset.key);};el.onchange=()=>{remember();const td=el.closest('td'),r=s.rows[+td.dataset.row],k=td.dataset.key;let v=el.value===''?null:el.type==='number'?Number(el.value):el.value;if(v!=null&&el.type==='number'&&!Number.isFinite(v)){notice('숫자를 확인하세요.',true);history.pop();return;}if(data.layout==='unity'&&bools.has(k)&&v!=null)v=v==='TRUE';r[k]=v;edited();table();};});
 $('editorTable').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{remember();const i=+b.dataset.copy,r=clone(s.rows[i]);if(sheet==='공격 만들기'){let id=+r.PatternID+1;while(s.rows.some(x=>same(x.PatternID,id)))id++;r.PatternID=id;r.Name=(r.Name||'공격')+' 복사';}if(['대사','대화 그룹','전투 대사 연결'].includes(sheet)){const key={대사:'DialogueID','대화 그룹':'GroupID','전투 대사 연결':'TriggerID'}[sheet];r[key]=Math.max(0,...s.rows.map(x=>+x[key]||0))+1;if(sheet==='대사')r.Order=Math.max(0,...s.rows.filter(x=>same(x.GroupID,r.GroupID)).map(x=>+x.Order||0))+1;if(sheet==='전투 대사 연결')r.Enabled=data.layout==='unity'?false:'끄기';}if(sheet==='범위 풀')r.Candidate=Math.max(0,...s.rows.filter(x=>same(x.ShapePoolID,r.ShapePoolID)).map(x=>+x.Candidate||0))+1;s.rows.splice(i+1,0,r);edited();table();});
 $('editorTable').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{remember();s.rows.splice(+b.dataset.delete,1);edited();table();notice('행을 삭제했어요. ‘편집 취소’로 되돌릴 수 있습니다.');});
}
function validationOptions(){return {monsterID:$('monster').value,phaseID:mode==='pattern'?+$('phase').value:null,patternID:mode==='pattern'?+$('pattern').value:null,preview:mode==='pattern'};}
function updateInfo(){if(!data)return;updatePoolInfo();const m=selectedMonster(),p=selectedPattern(),speed=m?.AttackSpeed;const time=v=>typeof v==='number'&&speed>0?Math.round(v/speed)+' ms':'미정';$('timings').innerHTML=[['피할 시간',mode==='pattern'?time(fallback(p?.ResponseMs,rule(data,'DefaultResponseMs'))):'패턴별'],['공격 후 대기',time(m?.RecoveryMs)],['공격 속도',speed?speed+'×':'미정']].map(([a,b])=>`<div class="timecard"><small>${a}</small><b>${b}</b></div>`).join('');const v=validate(data,validationOptions());$('issues').innerHTML=(v.errors.length?v.errors.map(e=>`<div>${esc(e)}</div>`).join(''):'<div class="ok">선택한 조건으로 실행할 수 있어요.</div>')+v.warnings.map(e=>`<div>${esc(e)}</div>`).join('');$('enemyName').textContent=battle?.monster?.Name||m?.Name||'몬스터 선택';$('assetInfo').textContent='모션 이름은 리소스 파일명 또는 zombie_attack / sans_push / sans_blaster를 사용할 수 있어요. 소리: MonsterAttack.wav, Enemy_Warning.wav 등 제공 파일명.';}
async function start(){dialoguePreview=null;if($('sound').checked){if(JSON.parse($('host-data').textContent).mode==='story')scene.unlock();else await scene.unlock();}else scene.audioError=null;scene.volume($('sound').checked,+$('volume').value);try{const next=new Battle(data);next.start($('monster').value,+$('phase').value,mode==='pattern'?{patternID:+$('pattern').value,damage:$('testDamage').value===''?null:+$('testDamage').value,beauty:$('beauty').value}:{beauty:$('beauty').value});battle=next;$('pause').textContent=battle.paused?'계속하기':'일시정지';$('battleArea').focus();notice(mode==='pattern'?'패턴 시험 시작. 현재 선택한 패턴을 반복하며 시험 피해는 엑셀에 저장하지 않습니다.':'전투 시작. 예고가 모두 나온 뒤 타격합니다. 방향키 이동 · F 패링/가드 · SPACE 빈틈공격');if(scene.audioError)notice('전투는 시작했지만 소리 재생에 실패했어요: '+scene.audioError,true);}catch(e){notice(e.message,true);updateInfo();}}
function setMode(next){pauseBattle();mode=next;$('modeBattle').classList.toggle('active',mode==='battle');$('modePattern').classList.toggle('active',mode==='pattern');$('previewOptions').hidden=mode!=='pattern';updateInfo();}
function download(bytes,name){const url=URL.createObjectURL(new Blob([bytes],{type:OfflineBook.macro?'application/vnd.ms-excel.sheet.macroEnabled.12':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
let versionRoot=null,versionBusy=false,versionTemplates=null,pendingWorkbook=null;
// Play uses the host's validated data. Excel templates are only needed for a version export.
async function prepareVersionTables(){
 if(!versionTemplates){
  const decode=id=>Uint8Array.from(atob($(id).textContent.trim()),c=>c.charCodeAt(0));
  versionTemplates=TableVersions.init(decode('embedded-authoring'),decode('embedded-workbook'),JSON.parse($('embedded-schema').textContent)).catch(e=>{versionTemplates=null;throw e;});
 }
 await versionTemplates;
 if(pendingWorkbook){await TableVersions.adopt(pendingWorkbook.bytes,pendingWorkbook.data);pendingWorkbook=null;}
}
async function chooseVersionFolder(){
 if(!await requireCombatOwner())return null;
 if(!window.showDirectoryPicker){notice('이 브라우저는 폴더에 직접 저장할 수 없어요. 버전 ZIP 받기로 내려받아 바탕화면 데이터테이블 폴더에 압축을 풀어 주세요.');return null;}
 try{versionRoot=await window.showDirectoryPicker({id:'yachacha-table-root',mode:'readwrite',startIn:'desktop'});$('versionFolder').textContent='저장 위치: '+versionRoot.name;return versionRoot;}catch(e){if(e.name!=='AbortError')notice('폴더 선택 실패: '+e.message+' · 버전 ZIP 받기를 사용할 수 있어요.',true);return null;}
}
async function exportBook(asZip=false){
 if(!await requireCombatOwner())return;
 pauseBattle();if(versionBusy)return;const intent=$('changeIntent').value.trim();if(!intent){notice('이번 변경의 의도를 먼저 적어 주세요. 변경된 시트·컬럼·이전 값·이후 값은 자동으로 기록됩니다.',true);$('changeIntent').focus();return;}
 versionBusy=true;$('exportBook').disabled=true;$('exportZip').disabled=true;
 try{
  if(!asZip&&!window.showDirectoryPicker)asZip=true;
  if(!asZip&&!versionRoot&&!(await chooseVersionFolder()))return;
  if(!await requireCombatOwner())return;notice('엑셀 버전을 준비하고 있어요. 잠시 기다려 주세요.');await prepareVersionTables();const version=asZip?TableVersions.stamp():await TableVersions.uniqueVersion(versionRoot),result=await TableVersions.prepare(data,intent,version);
  if(!await requireCombatOwner())return;if(asZip){const bytes=await TableVersions.zip(result),url=URL.createObjectURL(new Blob([bytes],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download=version+'_데이터테이블.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);notice('두 엑셀과 변경 이력을 ZIP으로 내려받습니다. 바탕화면 데이터테이블 폴더에 압축을 풀어 주세요. 버전: '+version);}
  else{await TableVersions.writeDirectory(versionRoot,result);notice('두 엑셀과 변경 이력을 저장했어요: '+versionRoot.name+' / '+version);}
  await TableVersions.commit(result);$('savedVersion').textContent='기준 버전: '+version;baseline=clone(data);history=[];persist();table();$('changeIntent').value='';
 }catch(e){notice(e.message,true);}finally{versionBusy=false;applyCombatOwnerControls();}
}
async function loadBook(file){if(!await requireCombatOwner())return;if(!file||versionBusy)return;pauseBattle();dialoguePreview=null;try{const bytes=await file.arrayBuffer(),next=await OfflineBook.load(bytes,file.name);pendingWorkbook={bytes,data:clone(next)};data=next;baseline=clone(data);battle=null;history=[];sheet='공격 만들기';$('sourceName').textContent=file.name+(data.macro?' · 매크로 보존':'');$('savedVersion').textContent='기준 버전: 불러온 엑셀 · 저장 시 이력 확인';populate();tabs();table();persist();notice(file.name+' 불러오기 완료. 수정 후 변경 의도를 적고 버전 저장을 누르세요.');}catch(e){notice(e.message,true);}}
function draw(){if(!data)return;drawDialogue();updatePoolInfo();scene.volume($('sound').checked,+$('volume').value);scene.render(battle,character(),renderIdle);if(!battle)return;const b=battle,m=b.monster;$('enemyName').textContent=m.Name;$('phaseBadge').textContent=`${m.PhaseID}페이즈 · ${Number(b.pattern?.AttackSpeed??m.AttackSpeed).toFixed(2)}×`;
 for(const[id,txt,v,max]of [['enemyHP','enemyHPText',b.enemyHP,m.MaxHP],['gaugeBar','gaugeText',b.gauge,m.GaugeMax],['hpBar','hpText',b.hp,b.player.MaxHP],['guardBar','guardText',b.guard,b.player.GuardMax]]){$(id).style.width=Math.max(0,Math.min(100,v/max*100))+'%';$(txt).textContent=`${Math.ceil(v)} / ${max}`;}
 const plan=b.planInfo,next=b.queue[0];let state={recover:'다음 공격 준비',attack:b.forcedMoving?'강제 이동 중 → 끝나면 방향키로 탈출':!on(b.pattern?.CanDefend)?'방어 불가 · 위험 타일을 벗어나세요':'예고를 보고 이동하거나 F로 패링하세요',opening:(b.opportunities<=m.PlayerDodgeMissCount?'이번 빈틈 기회는 MISS · ':b.pending?'마무리 연타! 빈틈 종료 후 대사 · ':'빈틈! SPACE 연타 · ')+`${b.openingResult?.attempts||0}타`,openingResult:'연타 종료 · 대사를 마친 뒤 전환',victory:'승리 · 모든 페이즈 완료',defeat:'패배 · 값을 바꾸고 다시 시험하세요'}[b.state]||'준비';if(b.dialogueBlocking)state=b.dialogues?.active?.leadMs>0?'부활 연출 중 · 끝난 뒤 대사 시작':'대화 중 · 전투 시간 정지';if(b.paused)state='일시정지';$('battleState').textContent=state;$('patternText').textContent=b.pattern?`${b.pattern.PatternID} · ${b.pattern.Name} · 피해 ${b.pattern.HitDamage}`:'공격 대기';$('countdown').textContent=next?`타격까지 ${Math.max(0,Math.ceil(next.due-b.time))} ms`:b.state==='recover'?`대기 ${Math.max(0,Math.ceil(b.next-b.time))} ms`:b.state==='opening'?`빈틈 ${(b.gauge/b.rule('GroggyDrainPerSec')).toFixed(1)}초`:'—';$('beatFill').style.width=next?Math.min(100,Math.max(0,(b.time-next.previewAt)/(next.due-next.previewAt||1)*100))+'%':'0%';
 const key=b.events.map(e=>e.time+e.text).join('|');if(key!==lastLog){$('log').innerHTML=b.events.map(e=>`<div class="${e.kind}"><time>${(e.time/1000).toFixed(2)}</time>${esc(e.text)}</div>`).join('');lastLog=key;}
}
function frame(t){const dt=lastTime?Math.min(100,t-lastTime):0;lastTime=t;renderIdle+=dt;if(dialoguePreview)dialoguePreview.tick(dt);battle?.tick(dt);draw();requestAnimationFrame(frame);}
function editing(e){return ['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable;}
window.addEventListener('keydown',e=>{if(editing(e))return;if(e.key==='Enter'&&(dialoguePreview||battle?.dialogues)?.active){e.preventDefault();if(!e.repeat)(dialoguePreview||battle.dialogues).advance();return;}if(!battle)return;const k=e.key.toLowerCase(),moves={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};if(moves[k]){e.preventDefault();battle.move(...moves[k]);}if(k==='f'){e.preventDefault();if(!e.repeat)battle.setGuard(true);}if(e.code==='Space'){e.preventDefault();if(!e.repeat)battle.attack();}if(k==='escape'){e.preventDefault();$('pause').click();}});
window.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='f')battle?.setGuard(false);});window.addEventListener('blur',pauseBattle);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseBattle();});
$('start').onclick=start;$('pause').onclick=()=>{if(!battle)return;battle.paused=!battle.paused;battle.setGuard(false);if(!battle.paused){scene.unlock();}$('pause').textContent=battle.paused?'계속하기':'일시정지';$('battleArea').focus();};$('reset').onclick=()=>{scene.stop();dialoguePreview=null;battle=null;$('battleState').textContent='전투를 초기화했어요. 값을 적용해 다시 시작하세요.';$('patternText').textContent='공격 대기';$('countdown').textContent='—';$('phaseBadge').textContent='전투 준비';};
$('modeBattle').onclick=()=>setMode('battle');$('modePattern').onclick=()=>setMode('pattern');$('monster').onchange=()=>{battle=null;populate();};$('phase').onchange=()=>{battle=null;updateInfo();};$('pattern').onchange=()=>{pauseBattle();updateInfo();};$('character').onchange=()=>{};$('sound').onchange=()=>{if($('sound').checked)scene.unlock();else scene.stop();};
$('filter').oninput=table;$('addRow').onclick=()=>{remember();const s=data.sheets.find(s=>s.name===sheet);const r=Object.fromEntries(s.keys.map(k=>[k,null]));const key={대사:'DialogueID','대화 그룹':'GroupID','전투 대사 연결':'TriggerID'}[sheet];if(key)r[key]=Math.max(sheet==='대사'?900000:sheet==='대화 그룹'?80000:100000,...s.rows.map(x=>+x[key]||0))+1;if(sheet==='대사'){r.GroupID=+$('dialogueGroup').value||rows(data,'대화 그룹')[0]?.GroupID;r.Order=Math.max(0,...s.rows.filter(x=>same(x.GroupID,r.GroupID)).map(x=>+x.Order||0))+1;r.Speaker='몬스터';}if(sheet==='대화 그룹')Object.assign(r,{PlaybackMode:'순서대로',PauseCombat:'끄기',AdvanceMode:'자동',CPS:30,HoldMs:1500,GapMs:400,ActorEffect:'없음',FinishEffect:'없음'});if(sheet==='전투 대사 연결')Object.assign(r,{MonsterID:selectedMonster()?.MonsterID,EventType:'전투 시작',BeautyCondition:'공통',CooldownMs:0,MaxPerBattle:1,Enabled:'끄기'});s.rows.push(r);edited();table();$('tableWrap').scrollTop=99999;};$('undo').onclick=()=>{if(!history.length)return;data=history.pop();edited();table();};$('restore').onclick=()=>{if(!confirm('현재 작업본을 불러온 엑셀 값으로 되돌릴까요?'))return;remember();data=clone(baseline);edited();table();};
$('check').onclick=()=>{const v=validate(data);notice(v.errors.length?'전체 검사:\n'+v.errors.join('\n'):'전체 데이터의 연결과 값을 확인했어요.',!!v.errors.length);};$('importBook').onclick=async()=>{if(await requireCombatOwner())$('bookFile').click();};$('bookFile').onchange=e=>{loadBook(e.target.files[0]);e.target.value='';};$('exportBook').onclick=()=>exportBook(false);$('exportZip').onclick=()=>exportBook(true);$('chooseVersionFolder').onclick=chooseVersionFolder;
$('forceOpening').onclick=()=>{if(battle&&!['victory','defeat'].includes(battle.state))battle.open();};$('heal').onclick=()=>{if(battle){battle.hp=battle.player.MaxHP;battle.guard=battle.player.GuardMax;}};$('clearLog').onclick=()=>{if(battle)battle.events=[];};document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>battle?.move(...b.dataset.move.split(',').map(Number)));$('attackBtn').onclick=()=>battle?.attack();$('guardBtn').onpointerdown=e=>{e.preventDefault();e.target.setPointerCapture(e.pointerId);battle?.setGuard(true);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('guardBtn').addEventListener(ev,()=>battle?.setGuard(false));
window.lab={get dialoguePreview(){return dialoguePreview;},previewDialogue,loadDefault,get data(){return data;},get battle(){return battle;},get scene(){return scene;},start,exportBook,loadBook,validate,makePlan,OfflineBook,TableVersions};

function populateDialogue(){const selected=$('dialogueGroup').value,groups=rows(data,'대화 그룹');$('dialogueGroup').innerHTML=groups.map(g=>`<option value="${esc(g.GroupID)}">${g.GroupID} · ${esc(g.Name)}</option>`).join('');if(groups.some(g=>same(g.GroupID,selected)))$('dialogueGroup').value=selected;else if(groups.some(g=>g.GroupID===80016))$('dialogueGroup').value=80016;$('previewDialogue').disabled=!groups.length;}
function previewDialogue(){pauseBattle();const host={data,monster:selectedMonster(),options:{beauty:$('beauty').value},time:0};const next=new DialoguePlayer(host);if(!next.play(+$('dialogueGroup').value,{replace:true})){notice('이 그룹에는 아직 대사 내용이 없어요. 대사 시트에서 본문을 입력하세요.',true);return;}dialoguePreview=next;notice('대사 미리보기 중입니다. Enter 또는 다음 대사 버튼으로 진행하세요.');}
function drawDialogue(){const d=dialoguePreview||battle?.dialogues,a=d?.active,l=d?.line,speaker=l?.Speaker==='몬스터'?(d.host.monster?.Name||'몬스터'):l?.Speaker||'대사';const view=JSON.stringify([speaker,d?.visibleText,a?.group.GroupID,a?.index,a?.gap,!!dialoguePreview,d?.complete,d?.clock]);if(view===lastDialogueView)return;lastDialogueView=view;$('dialogueSpeaker').textContent=speaker;$('dialogueText').innerHTML=(d?.visibleGlyphs||[]).map((glyph,i)=>{if(glyph.char==='\n')return '<br>';const v=dialogueGlyphStyle(glyph,i,d.textClock);return `<span class="dialogueglyph" style="color:${v.color};font-size:${v.fontSize}px;opacity:${v.opacity};transform:translate(${v.x.toFixed(2)}px,${v.y.toFixed(2)}px) scale(${v.scale.toFixed(3)})">${esc(glyph.char)}</span>`;}).join('');$('dialogueText').setAttribute('aria-label',d?.visibleText||'');$('dialogueMeta').textContent=a?`${a.group.Name} · ${a.index+1}/${a.lines.length} · ${a.group.AdvanceMode}${a.pause?' · 전투 정지':''}`:'연결된 사건이 발생하면 대사가 나옵니다.';$('nextDialogue').disabled=!a||a.leadMs>0;$('nextDialogue').textContent=a?.leadMs>0?'부활 연출 재생 중':a&&!d.complete?'문장 바로 보기 · Enter':'다음 대사 · Enter';$('stopDialogue').hidden=!dialoguePreview;}
function updatePoolInfo(){if(!data)return;const p=battle?.pattern|| (mode==='pattern'?selectedPattern():null);let text='현재 전투에서 선택된 패턴의 실제 연결을 표시합니다.';if(p){if(p.RangeMode==='밀친 위치')text=`현재 공격 ${p.PatternID} · 플레이어 상대 위치로 범위 결정`;else if(!empty(p.TilePath))text=`현재 공격 ${p.PatternID} · 직접 경로 ${p.TilePath}`;else {const a=candidates(battle?.pattern?battle.data:data,p.ShapePoolID,battle?.pos??5);text=`현재 공격 ${p.PatternID} → 풀 ${p.ShapePoolID} · 활성 후보 ${a.map(c=>c.Candidate).join(', ')} · ${on(p.CanDefend)?'방어 가능':'방어 불가'}`;}if(mode==='pattern'&&selectedPattern()&&(!same(p.PatternID,selectedPattern().PatternID)||!same(p.ShapePoolID,selectedPattern().ShapePoolID)))text+=` / 다음 시험 선택 ${selectedPattern().PatternID} → 풀 ${selectedPattern().ShapePoolID}`;}if($('poolInfo').textContent!==text)$('poolInfo').textContent=text;}
async function loadDefault(){if(!await requireCombatOwner())return;if(!confirm('현재 작업본을 내장 마스터 테이블로 바꿀까요? 수정한 값이 필요하면 먼저 버전 저장을 하세요.'))return;const bytes=Uint8Array.from(atob($('embedded-authoring').textContent.trim()),c=>c.charCodeAt(0));await loadBook({name:'야차차_마스터테이블_작업용.xlsm',arrayBuffer:async()=>bytes.buffer});}
$('beauty').onchange=()=>{pauseBattle();notice('다음 전투부터 선택한 미용 결과의 대사를 사용합니다. 적용 후 시작을 누르세요.');};
$('previewDialogue').onclick=previewDialogue;$('nextDialogue').onclick=()=>{(dialoguePreview||battle?.dialogues)?.advance();drawDialogue();};$('stopDialogue').onclick=()=>{dialoguePreview=null;drawDialogue();};$('loadDefault').onclick=loadDefault;

let initializing=null,frameStarted=false;
async function init(){
 if(initializing)return initializing;
 initializing=Promise.resolve().then(async()=>{
  try{
   if(!data){data=clone(JSON.parse($('host-data').textContent).data);baseline=clone(data);}
   $('sourceName').textContent='통합 프로젝트의 전투 데이터';
   $('savedVersion').textContent='엑셀 기준 버전은 버전 저장 시 확인합니다';
   populate();tabs();table();persist();
   await scene.load();await hostReady();
   if(!frameStarted){frameStarted=true;requestAnimationFrame(frame);}
   $('retryCombat')?.remove();
   notice('전투 준비 완료. 엑셀을 불러와 수정하거나 현재 데이터를 버전으로 저장할 수 있어요.');
  }catch(e){
   notice('전투 준비 실패: '+e.message,true);notifyHost('load-error',{message:e.message});
   if(!$('retryCombat')){const retry=document.createElement('button');retry.id='retryCombat';retry.textContent='전투 화면 다시 준비';retry.onclick=()=>init();$('notice').after(retry);}
  }
 }).finally(()=>{initializing=null;});return initializing;
}
// The host bridge in the combined module must exist before initialization runs.
queueMicrotask(init);
