const HOST=JSON.parse(document.getElementById('host-data').textContent);let sentBattleEnd=false,hostSuspended=false,wasPaused=false;

let combatOwner=false,combatOwnerExpires=0,ownerExpiry=null;const ownerRequests=new Map();
function combatOwnerAllowed(){return combatOwner&&combatOwnerExpires>Date.now();}
function applyCombatOwnerControls(){clearTimeout(ownerExpiry);const allowed=combatOwnerAllowed();document.querySelectorAll('[data-owner-only]').forEach(b=>{b.disabled=versionBusy;b.setAttribute('aria-disabled',String(!allowed));b.title=allowed?'':'클릭해 비밀번호로 잠금 해제';});if(allowed)ownerExpiry=setTimeout(applyCombatOwnerControls,Math.max(0,combatOwnerExpires-Date.now()));}
function requireCombatOwner(){return new Promise(resolve=>{const requestID=crypto.randomUUID(),timer=setTimeout(()=>{ownerRequests.delete(requestID);combatOwner=false;applyCombatOwnerControls();resolve(false);},180000);ownerRequests.set(requestID,allowed=>{clearTimeout(timer);if(!allowed){combatOwner=false;applyCombatOwnerControls();}resolve(allowed);});notifyHost('owner-check',{requestID});});}

combatOwner=HOST.ownerAllowed===true;combatOwnerExpires=HOST.ownerExpires||0;
document.addEventListener('click',e=>{const button=e.target.closest?.('[data-owner-only]');if(button&&!combatOwnerAllowed()){e.preventDefault();e.stopImmediatePropagation();notifyHost('owner-prompt');}},true);
function notifyHost(type,extra={}){parent.postMessage({source:'yachacha-combat',token:HOST.token,type,...extra},'*');}
async function hostReady(){applyCombatOwnerControls();if(HOST.mode==='story'){document.body.classList.add('storyMode');await scene.loadRoom(HOST.visuals);$('monster').value=HOST.monsterID;populate();$('phase').value=rows(data,'몬스터 페이즈').find(m=>same(m.MonsterID,HOST.monsterID)&&on(m.IsInitial))?.PhaseID||1;$('beauty').value=HOST.beauty||'미용 성공';$('sound').checked=!!HOST.sound;const gate=document.createElement('div');gate.id='fightGate';gate.innerHTML='<small>가위 대신, 한 판의 인사</small><h2>야차 시작!</h2>';document.body.append(gate);notifyHost('sound',{key:'prep'});scene.render(null,character());setTimeout(async()=>{gate.remove();await start();notifyHost('sound',{key:'clash'});if(hostSuspended)pauseBattle();},1500);}notifyHost('ready');}
addEventListener('message',e=>{if(e.source!==parent||e.data?.token!==HOST.token)return;const m=e.data;if(m.type==='owner-state'){combatOwner=m.allowed===true;combatOwnerExpires=m.expiresAt||0;applyCombatOwnerControls();}if(m.type==='owner-result'){ownerRequests.get(m.requestID)?.(m.allowed===true);ownerRequests.delete(m.requestID);}if(m.type==='snapshot'){document.activeElement?.blur();notifyHost('snapshot',{data:clone(data),requestID:m.requestID});}if(m.type==='sound'){$('sound').checked=m.enabled;scene.volume(m.enabled,+$('volume').value);}if(m.type==='suspend'){if(!hostSuspended){wasPaused=battle?.paused||false;hostSuspended=true;}pauseBattle();}if(m.type==='resume'&&hostSuspended){hostSuspended=false;if(battle&&!wasPaused){battle.paused=false;$('pause').textContent='일시정지';$('battleArea').focus();}}});
// Keep a visible resume control when focus changes pause a story battle.
if(HOST.mode==='story'){document.body.classList.add('storyMode');const control=document.createElement('div');control.className='storyPause';$('battleArea').prepend(control);control.append($('pause'));}
const originalFrame=frame;frame=t=>{originalFrame(t);if(HOST.mode==='story')$('dialogueBox').classList.toggle('speaking',!!battle?.dialogues?.active&&battle.dialogues.active.leadMs<=0);if(HOST.mode==='story'&&battle&&!sentBattleEnd&&['victory','defeat'].includes(battle.state)&&!battle.dialogues?.active&&!battle.dialogues?.queue.length&&!battle.dialogueBlocking){sentBattleEnd=true;setTimeout(()=>notifyHost('battle-end',{outcome:battle.state,stats:clone(battle.stats)}),500);}};

if(HOST.mode==='story'){for(const event of ['pointerdown','keydown'])addEventListener(event,()=>{scene.unlock();},{once:true});}
