const HOST=JSON.parse(document.getElementById('host-data').textContent);let sentBattleEnd=false,hostSuspended=false,wasPaused=false;
function notifyHost(type,extra={}){parent.postMessage({source:'yachacha-combat',token:HOST.token,type,...extra},'*');}
async function hostReady(){data=clone(HOST.data);baseline=clone(data);populate();tabs();table();persist();if(HOST.mode==='story'){document.body.classList.add('storyMode');await scene.loadRoom(HOST.visuals);$('monster').value=HOST.monsterID;populate();$('phase').value=rows(data,'몬스터 페이즈').find(m=>same(m.MonsterID,HOST.monsterID)&&on(m.IsInitial))?.PhaseID||1;$('beauty').value=HOST.beauty||'미용 성공';$('sound').checked=!!HOST.sound;const gate=document.createElement('div');gate.id='fightGate';gate.innerHTML='<small>가위 대신, 한 판의 인사</small><h2>야차 시작!</h2>';document.body.append(gate);notifyHost('sound',{key:'prep'});scene.render(null,character());setTimeout(async()=>{gate.remove();await start();notifyHost('sound',{key:'clash'});if(hostSuspended)pauseBattle();},1500);}notifyHost('ready');}
addEventListener('message',e=>{if(e.source!==parent||e.data?.token!==HOST.token)return;const m=e.data;if(m.type==='snapshot'){document.activeElement?.blur();notifyHost('snapshot',{data:clone(data),requestID:m.requestID});}if(m.type==='sound'){$('sound').checked=m.enabled;scene.volume(m.enabled,+$('volume').value);}if(m.type==='suspend'){if(!hostSuspended){wasPaused=battle?.paused||false;hostSuspended=true;}pauseBattle();}if(m.type==='resume'&&hostSuspended){hostSuspended=false;if(battle&&!wasPaused){battle.paused=false;$('pause').textContent='일시정지';$('battleArea').focus();}}});
// Keep a visible resume control when focus changes pause a story battle.
if(HOST.mode==='story'){document.body.classList.add('storyMode');const control=document.createElement('div');control.className='storyPause';$('battleArea').prepend(control);control.append($('pause'));}
const originalFrame=frame;frame=t=>{originalFrame(t);if(HOST.mode==='story')$('dialogueBox').classList.toggle('speaking',!!battle?.dialogues?.active&&battle.dialogues.active.leadMs<=0);if(HOST.mode==='story'&&battle&&!sentBattleEnd&&['victory','defeat'].includes(battle.state)&&!battle.dialogues?.active&&!battle.dialogues?.queue.length&&!battle.dialogueBlocking){sentBattleEnd=true;setTimeout(()=>notifyHost('battle-end',{outcome:battle.state,stats:clone(battle.stats)}),500);}};

if(HOST.mode==='story'){for(const event of ['pointerdown','keydown'])addEventListener(event,()=>{scene.unlock();},{once:true});}
