import {loadAudioBytes} from '../media.js';
const blendColor=(a,b,t)=>'#'+[1,3,5].map(i=>Math.round(parseInt(a.slice(i,i+2),16)*(1-t)+parseInt(b.slice(i,i+2),16)*t).toString(16).padStart(2,'0')).join('');
class GameScene{
 constructor(canvas,assets){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.assets=assets;this.images={};this.sounds={};this.voices=new Set();this.seen=0;this.battle=null;this.cues=[];this.audioReady=false;}
 async load(){await Promise.all(Object.entries(this.assets.images).map(async([key,spec])=>{const img=new Image();img.src=spec.src;await img.decode();if(spec.chroma){const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const g=c.getContext('2d');g.drawImage(img,0,0);const pixels=g.getImageData(0,0,c.width,c.height),bg=[...pixels.data.slice(0,3)];for(let i=0;i<pixels.data.length;i+=4)if(bg.every((x,j)=>Math.abs(pixels.data[i+j]-x)<3))pixels.data[i+3]=0;g.putImageData(pixels,0,0);this.images[key]=c;}else this.images[key]=img;}));}
 async unlock(){try{this.audio??=new (window.AudioContext||window.webkitAudioContext)();if(!this.master){this.master=this.audio.createGain();this.master.connect(this.audio.destination);}await this.audio.resume();if(!this.loadingSounds)this.loadingSounds=Promise.all(Object.entries(this.assets.sounds).map(async([key,s])=>{this.sounds[key]=await this.audio.decodeAudioData(await loadAudioBytes(s.src));}));await this.loadingSounds;this.audioReady=true;this.audioError=null;}catch(e){this.loadingSounds=null;this.audioError=e.message;}}
 volume(enabled,value){this.enabled=enabled;if(this.master)this.master.gain.value=enabled?value/100*.75:0;}
 stop(){for(const s of this.voices)try{s.stop();}catch{}this.voices.clear();}
 play(kind,b,cue){if(!this.audioReady||!this.enabled)return;let key=kind==='openingHit'?'strike':kind;if(kind==='strike'&&b?.planInfo?.extra.SoundKey){const wanted=b.planInfo.extra.SoundKey;key=Object.keys(this.assets.sounds).find(k=>k===wanted||this.assets.sounds[k].file===wanted||this.assets.sounds[k].file.replace(/\.wav$/i,'')===wanted)||key;}const buffer=this.sounds[key];if(buffer){const s=this.audio.createBufferSource();s.buffer=buffer;if(kind==='telegraph'&&cue?.count>1&&b?.pattern.RangeMode==='범위 반복')s.playbackRate.value=1+(cue.index-1)*.1;s.connect(this.master);s.onended=()=>this.voices.delete(s);this.voices.add(s);s.start();}else if(['ready','guard','miss','dodge'].includes(kind)){const o=this.audio.createOscillator(),g=this.audio.createGain();o.type='sine';o.frequency.value=kind==='ready'?1200:kind==='guard'?200:400;g.gain.setValueAtTime(.08,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+.08);o.connect(g);g.connect(this.master);o.start();o.stop(this.audio.currentTime+.1);this.voices.add(o);o.onended=()=>this.voices.delete(o);}}
 point(t){return {x:358+((t-1)%3)*107+48,y:116+Math.floor((t-1)/3)*80+36};}
 sprite(key,frame,x,feet,height,alpha=1){const s=this.assets.images[key],img=this.images[key];if(!s||!img)return;frame=Math.max(0,Math.min(s.count-1,Math.floor(frame)));const sx=s.crop?.[0]??(frame%s.cols)*s.fw,sy=s.crop?.[1]??Math.floor(frame/s.cols)*s.fh,w=s.fw/s.fh*height,g=this.ctx;g.save();g.globalAlpha=alpha;g.imageSmoothingEnabled=false;g.drawImage(img,sx,sy,s.fw,s.fh,x-w/2,feet-height,w,height);g.restore();}
 render(b,character,now=0){if(this.battle!==b){this.stop();this.battle=b;this.seen=0;this.cues=[];}if(b){for(const c of b.cues){if(c.id<=this.seen)continue;this.seen=c.id;this.cues.push(c);if(!b.paused)this.play(c.kind,b,c);}this.cues=this.cues.filter(c=>c.kind==='openingHit'?b.visualTime-c.visualTime<850:b.time-c.time<1600);if(b.paused)this.stop();}
  const g=this.ctx,t=b?.time??now,vt=b?.visualTime??now,actor=b?.dialogues?.active?.group.ActorEffect,finale=b?.finale;g.clearRect(0,0,720,410);const bg=g.createLinearGradient(0,0,720,400);bg.addColorStop(0,'#243c3c');bg.addColorStop(1,'#15282e');g.fillStyle=bg;g.fillRect(0,0,720,410);
  g.fillStyle='#0d1d25';g.fillRect(0,0,720,63);g.fillStyle='#768f95';g.font='12px 맑은 고딕';g.fillText('YACHACHA / BATTLE LAB',22,28);g.fillStyle='#dfc695';g.fillText(b?.options.patternID?'패턴 시험 · 엑셀 값 유지':'몬스터 전투 · 엑셀 비중 적용',22,49);
  g.strokeStyle='#354e53';for(let y=84;y<410;y+=35){g.beginPath();g.moveTo(0,y);g.lineTo(720,y+35);g.stroke();}const light=g.createRadialGradient(148,235,5,148,235,175);light.addColorStop(0,'#c7b98c77');light.addColorStop(1,'#c7b98c00');g.fillStyle=light;g.fillRect(0,64,340,320);g.fillStyle='#40544a';g.beginPath();g.ellipse(149,305,105,28,0,0,Math.PI*2);g.fill();g.strokeStyle='#d0b775';g.lineWidth=2;g.stroke();
  const plan=b?.planInfo,attacking=b?.state==='attack',combo=b?.pattern?.RangeMode==='범위 반복'&&plan?.groups?.length>1;
  const upcoming=b?.queue?.[0],pulse=combo?telegraphVisual(b):null,numberOverlays=[];let warning=attacking?(b.preview??upcoming):null;if(attacking&&plan&&t>=plan.firstHit)warning=upcoming;if(combo)warning=pulse?b.preview:null;
  for(let tile=1;tile<=9;tile++){const p=this.point(tile),broken=b?.broken[tile]>t,warn=warning?.tiles.includes(tile),hit=b?.flashUntil>t&&b?.flash.includes(tile);const x=p.x-47,y=p.y-35;
   g.save();if(warn&&combo){g.shadowColor='#00bcd4';g.shadowBlur=20*pulse.alpha;}g.fillStyle=broken?'#101d24':hit?'#ff2424':warn?(combo?blendColor('#314b53','#00bcd4',pulse.alpha):!on(b.pattern.CanDefend)?'#70465f':'#796239'):'#314b53';g.fillRect(x,y,95,72);g.strokeStyle=hit?'#ffffff':warn?(combo?blendColor('#607475','#00bcd4',pulse.alpha):!on(b.pattern.CanDefend)?'#ed9fc6':'#edd094'):'#607475';g.lineWidth=warn||hit?2:1;g.strokeRect(x+.5,y+.5,94,71);g.restore();
   g.font='11px monospace';g.fillStyle='#a3b5b5';g.fillText(String(tile),x+7,y+15);
   if(broken){g.strokeStyle='#56717a';g.beginPath();g.moveTo(x+25,y+5);g.lineTo(x+58,y+28);g.lineTo(x+40,y+42);g.lineTo(x+64,y+66);g.stroke();g.fillStyle='#acb7b2';g.font='12px monospace';g.fillText(((b.broken[tile]-t)/1000).toFixed(1)+'s',x+30,y+53);}
   if(warn&&!broken&&combo)numberOverlays.push({p,pulse});
   if(warn&&!broken&&!combo){const progress=Math.max(0,Math.min(1,(t-warning.previewAt)/Math.max(1,warning.due-warning.previewAt)));g.strokeStyle='#ffe0a6';g.lineWidth=2;g.beginPath();g.arc(p.x,p.y,Math.max(5,29*(1-progress)),0,Math.PI*2);g.stroke();g.fillStyle='#ffe5b3';g.font='bold 18px 맑은 고딕';g.fillText(String(warning.index),p.x+25,p.y+22);g.fillRect(x,y+68,95*progress,3);}
  }
  const labels={zombie:'취준좀비',drunk:'취객',sans:'샌즈',unknown:'리소스 미연결'};
  let ex=148,ey=301,asset=character+'_idle',frame=0,height=character==='drunk'?178:146;
  if(character==='drunk'){asset='drunk_'+Math.floor(t/200)%4;height=180;}
  if(plan?.motionStarted&&['attack','recover'].includes(b.state)&&t<=plan.lastHit+220/(plan.speed??b.monster.AttackSpeed)){const displayEnd=plan.lastHit+220/(plan.speed??b.monster.AttackSpeed);let p=Math.max(0,Math.min(.999,(t-plan.motionStart)/Math.max(1,displayEnd-plan.motionStart)));const e=plan.extra;
   asset=character==='sans'?(b.pattern.RangeMode==='밀친 위치'?'sans_push':'sans_blaster'):character==='zombie'?'zombie_attack':asset;
   if(e.MotionKey){const custom=Object.keys(this.assets.images).find(k=>k===e.MotionKey||this.assets.images[k].file===e.MotionKey||this.assets.images[k].file.replace(/\.png$/i,'')===e.MotionKey);if(custom)asset=custom;}
   frame=p*(this.assets.images[asset]?.count??1);if(asset==='zombie_attack')frame=t<plan.firstHit?Math.min(1,Math.floor((t-plan.motionStart)/Math.max(1,plan.firstHit-plan.motionStart)*2)):2+Math.min(4,(t-plan.firstHit)/Math.max(1,displayEnd-plan.firstHit)*5);if(asset==='sans_push'||asset==='sans_blaster')frame=t<plan.firstHit?Math.min(1,Math.floor((t-plan.motionStart)/Math.max(1,plan.firstHit-plan.motionStart)*2)):2;height=character==='sans'?195:character==='zombie'?175:180;
   if(e.MoveType==='대상까지'||e.MoveType==='고정 거리'){const pt=this.point(plan.motionTarget),distance=e.MoveType==='고정 거리'?e.MoveDistance*107:Math.hypot(pt.x-148,pt.y+22-301),d=Math.hypot(pt.x-148,pt.y+22-301)||1,targetX=148+(pt.x-148)/d*distance,targetY=301+(pt.y+22-301)/d*distance;const duration=Math.max(1,Math.min(plan.firstHit-plan.motionStart,e.MoveSpeed?distance/(e.MoveSpeed*107*(plan.speed??b.monster.AttackSpeed))*1000:plan.firstHit-plan.motionStart));let v=Math.min(1,(t-plan.motionStart)/duration);if(t>plan.lastHit)v*=Math.max(0,1-(t-plan.lastHit)/(displayEnd-plan.lastHit));ex+=(targetX-ex)*v;ey+=(targetY-ey)*v;}
   if(character==='drunk')ex+=Math.sin(p*Math.PI)*25;
  }else{ey+=Math.sin((actor?vt:t)/240)*2;}
  let actorAlpha=b?.actorDead?0:1;
  if(actor==='비틀거림'){ex+=Math.sin(vt/300)*9;ey+=Math.cos(vt/350)*4;if(character==='drunk')asset='drunk_'+Math.floor(vt/230)%4;}
  if(actor==='놀람'){ey-=Math.abs(Math.sin(vt/140))*6;}
  if(actor==='식은땀')ex+=Math.sin(vt/75)*1.2;
  if(finale?.type==='소멸'){const age=vt-finale.start,p=Math.min(1,age/1200);if(character==='sans'){asset='sans_dead';frame=Math.min(6,Math.floor(p*7));height=195;}actorAlpha=Math.max(0,1-Math.max(0,p-.65)/.35);}
  const reviving=b?.entryEffect?.type==='부활'&&vt<b.entryEffect.end;if(reviving){const p=Math.max(0,Math.min(1,(vt-b.entryEffect.start)/(b.entryEffect.end-b.entryEffect.start)));if(this.assets.images[character+'_revive']){asset=character+'_revive';frame=p*this.assets.images[asset].count;height=196;}else{ey+=60*(1-p);actorAlpha=p;}ex=148;}
  const feedback=[...this.cues].reverse().find(c=>['parry','hit','guard','miss','damage','opening'].includes(c.kind));
  if(b?.state==='opening'&&!b?.dialogueBlocking&&!b?.actorDead){ex+=Math.sin(t/80)*3;g.fillStyle='#f0d081';g.font='bold 17px 맑은 고딕';g.textAlign='center';g.fillText('빈틈!',148,103);g.textAlign='left';}
  if(character==='unknown'){g.fillStyle='#50616a';g.fillRect(ex-28,ey-105,56,95);g.fillStyle='#c2cfca';g.font='30px sans-serif';g.fillText('?',ex-10,ey-58);}else{g.save();if(pulse){g.shadowColor='#00bcd4';g.shadowBlur=24*pulse.alpha;}this.sprite(asset,frame,ex,ey,height,actorAlpha);g.restore();}
  if(actor==='식은땀'&&actorAlpha>0){g.save();g.fillStyle='#8BE9FD';g.shadowColor='#8BE9FD';g.shadowBlur=5;for(let i=0;i<3;i++){const v=(vt/900+i*.33)%1,x=ex+29+i*9,y=ey-height+30+v*38;g.globalAlpha=(1-v)*.95;g.beginPath();g.moveTo(x,y-7);g.quadraticCurveTo(x+8,y+7,x,y+9);g.quadraticCurveTo(x-7,y+7,x,y-7);g.fill();}g.restore();}
  if(finale?.type==='소멸'&&vt-finale.start<1600){g.save();const a=(vt-finale.start)/1200;g.fillStyle='#E9F8FF';for(let i=0;i<24;i++){g.globalAlpha=Math.max(0,1-a)*.8;g.fillRect(ex+Math.sin(i*7.4)*(15+a*95),ey-80+Math.cos(i*8)*(25+a*70)-a*45,2+i%3,2+i%3);}g.restore();}
  g.fillStyle='#d7dcca';g.font='12px 맑은 고딕';g.textAlign='center';g.fillText(labels[character]||character,148,346);g.textAlign='left';
  let pp=this.point(b?.pos??5);const push=plan?.push;if(attacking&&push?.started&&!push.done){const from=this.point(push.from),to=this.point(push.dest),p=Math.min(1,(t-push.start)/Math.max(1,push.end-push.start));pp={x:from.x+(to.x-from.x)*p,y:from.y+(to.y-from.y)*p};}
  let player='player_idle',pf=Math.floor(t/120)%9;if(b?.guardHeld){player='player_guard';pf=4;}if(feedback&&t-feedback.time<300&&feedback.kind==='hit'){player='player_hit';pf=Math.floor((t-feedback.time)/75);}if(feedback&&t-feedback.time<400&&feedback.kind==='damage'){player='player_attack';pf=Math.floor((t-feedback.time)/25);}
  this.sprite(player,pf,pp.x-9,pp.y+30,137);if(b?.guardHeld){g.strokeStyle='#a9d7fa';g.lineWidth=3;g.beginPath();g.ellipse(pp.x,pp.y-10,34,47,0,0,Math.PI*2);g.stroke();}
  if(plan?.extra.Effect==='블래스터 레이저'){const life=fallback(plan.extra.EffectMs,500)/(plan.speed??b.monster.AttackSpeed);for(const c of this.cues.filter(c=>c.kind==='strike'&&t-c.time<life)){this.sprite('blaster',0,290,143,75);for(const tile of c.tiles){const pt=this.point(tile);g.save();g.globalAlpha=Math.max(0,1-(t-c.time)/Math.max(life,1));g.strokeStyle='#73d5ed';g.lineWidth=20;g.beginPath();g.moveTo(293,133);g.lineTo(pt.x,pt.y);g.stroke();g.strokeStyle='#f5ffff';g.lineWidth=8;g.stroke();g.restore();}}}
  if(feedback&&t-feedback.time<550){const words={parry:'PARRY!',hit:'HIT',guard:'GUARD',miss:'MISS',damage:'빈틈공격',opening:'빈틈!'};g.save();g.globalAlpha=1-(t-feedback.time)/550;g.fillStyle=feedback.kind==='hit'?'#ffac96':'#ffe0a1';g.strokeStyle='#13232d';g.lineWidth=4;g.font='bold 27px 맑은 고딕';g.textAlign='center';const y=92-(t-feedback.time)/40;g.strokeText(words[feedback.kind],510,y);g.fillText(words[feedback.kind],510,y);g.restore();}
  // Independent per-hit numbers: overkill remains a valid visual hit until the window closes.
  for(const c of this.cues.filter(c=>c.kind==='openingHit').slice(-12)){
   const age=vt-c.visualTime,p=Math.max(0,age/850);if(p>=1)continue;
   const lane=(c.hit-1)%5,x=ex+(lane-2)*23,y=ey-height+24-lane*9-p*88;
   g.save();g.globalAlpha=p<.6?1:(1-p)/.4;g.translate(x,y);const scale=1+Math.max(0,1-age/120)*.45;g.scale(scale,scale);g.rotate(((c.hit%3)-1)*.045);
   g.font=`bold ${c.value>=100000?29:25}px 맑은 고딕`;g.textAlign='center';g.strokeStyle='#351216';g.lineWidth=5;g.shadowColor='#ff714b';g.shadowBlur=8;g.strokeText(String(c.value),0,0);g.fillStyle=c.hit%2?'#fff4c3':'#ffad7f';g.fillText(String(c.value),0,0);g.restore();
  }
  for(const {p,pulse}of numberOverlays){g.save();g.globalAlpha=pulse.numberAlpha;g.translate(p.x,p.y);g.scale(pulse.scale,pulse.scale);g.font='bold 46px 맑은 고딕';g.textAlign='center';g.textBaseline='middle';g.shadowColor='#00bcd4';g.shadowBlur=18;g.strokeStyle='#17232b';g.lineWidth=3;g.strokeText(pulse.label,0,0);g.fillStyle='#ffffff';g.fillText(pulse.label,0,0);g.restore();}
  g.fillStyle='#9cb6b8';g.font='11px 맑은 고딕';g.fillText(combo?'파란 숫자 N → 1 · 0.4초 점멸 · 예고 후 같은 박자로 타격':'예고를 보고 이동하거나, 타격 직전에 F',358,389);
  if(b?.paused){g.fillStyle='#081a26aa';g.fillRect(0,64,720,346);g.fillStyle='#edf1d7';g.font='bold 22px 맑은 고딕';g.textAlign='center';g.fillText('일시정지',360,218);g.textAlign='left';}
  else if(b?.dialogueBlocking){g.fillStyle='#11282ee8';g.fillRect(215,70,290,29);g.fillStyle='#f1dcae';g.font='12px 맑은 고딕';g.textAlign='center';g.fillText(reviving?'부활 중 · 연출 후 대사':b.dialogues?.active?'대화 중 · 전투 시간 정지':'마무리 연출 · 전투 시간 정지',360,90);g.textAlign='left';}
  if(finale?.type==='소울 해금 연출'&&vt<finale.end){g.save();const age=vt-finale.start,a=Math.min(1,age/500,(finale.end-vt)/700);g.globalAlpha=Math.max(0,a);g.fillStyle='#0c202bed';g.fillRect(160,117,400,181);g.strokeStyle='#edca80';g.strokeRect(160.5,117.5,399,180);const y=177+Math.sin(vt/240)*4;g.fillStyle='#ffe3a0';g.shadowColor='#f5bb58';g.shadowBlur=22;g.beginPath();g.moveTo(360,y-22);g.lineTo(375,y);g.lineTo(360,y+23);g.lineTo(345,y);g.closePath();g.fill();g.shadowBlur=0;g.textAlign='center';g.font='bold 20px 맑은 고딕';g.fillText('몬스터 소울 해금 · '+(b.monster?.Name||'몬스터'),360,239);g.fillStyle='#b8cac8';g.font='11px 맑은 고딕';g.fillText('연출 미리보기 · 실제 보상 지급표는 별도',360,271);g.restore();}
 }
}
