class SalonAudio{
 constructor(sources){this.sources=sources;this.cache={};this.enabled=true;this.track=null;this.wanted=null;this.epoch=0;this.voices=new Set();}
 async unlock(){try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();if(!this.master){this.master=this.ctx.createGain();this.master.gain.value=this.enabled?.6:0;this.master.connect(this.ctx.destination);}await this.ctx.resume();return true;}catch{return false;}}
 async buffer(key){if(!this.sources[key]||!this.ctx)return null;return this.cache[key]??=(async()=>{const bytes=Uint8Array.from(atob(this.sources[key].split(',')[1]),c=>c.charCodeAt(0));return this.ctx.decodeAudioData(bytes.buffer);})().catch(e=>{this.error=e.message;return null;});}
 enable(on){this.enabled=on;if(this.master)this.master.gain.setTargetAtTime(on?.6:0,this.ctx.currentTime,.08);if(on){this.unlock().then(()=>{if(this.wanted&&!this.track)this.music(this.wanted);});}}
 async music(key){this.wanted=key;if(this.track?.key===key)return;const version=++this.epoch;if(!this.ctx)return;const buffer=await this.buffer(key);if(version!==this.epoch||!buffer)return;const now=this.ctx.currentTime,previous=this.track;if(previous){previous.gain.gain.cancelScheduledValues(now);previous.gain.gain.setTargetAtTime(0,now,.18);previous.src.stop(now+1);}
 const src=this.ctx.createBufferSource(),gain=this.ctx.createGain();src.buffer=buffer;src.loop=true;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.34,now+.65);src.connect(gain).connect(this.master);src.start();src.onended=()=>{src.disconnect();gain.disconnect();};this.track={key,src,gain};}
 async effect(key){if(!this.enabled||!this.ctx)return;try{if(key==='glass'||key==='crash'){this.synthesize(key);return;}const buffer=await this.buffer(key);if(!buffer||!this.enabled)return;const src=this.ctx.createBufferSource(),gain=this.ctx.createGain();gain.gain.value=key.startsWith('foot')?.7:.8;src.buffer=buffer;src.connect(gain).connect(this.master);this.voices.add(src);src.onended=()=>{this.voices.delete(src);src.disconnect();gain.disconnect();};src.start();}catch(e){this.error=e.message;}}
 synthesize(key){const ctx=this.ctx,now=ctx.currentTime,glass=key==='glass';const duration=glass?.58:.22,buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const p=i/data.length;data[i]=(Math.random()*2-1)*Math.pow(1-p,glass?3:5)*.24;}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();src.buffer=buffer;filter.type=glass?'highpass':'lowpass';filter.frequency.value=glass?2400:230;src.connect(filter).connect(this.master);src.start();if(glass)for(const hz of [1800,2600,3900,5600]){const osc=ctx.createOscillator(),g=ctx.createGain();osc.type='sine';osc.frequency.value=hz;g.gain.setValueAtTime(.045,now);g.gain.exponentialRampToValueAtTime(.0001,now+.4);osc.connect(g).connect(this.master);osc.start();osc.stop(now+.45);}}
}
